(async () => { const sl = ms => new Promise(r => setTimeout(r, ms)); const D = window.__datavix, S = D.S, errs = [], out = {}; console.error = (...a) => errs.push(a.map(String).join(' ').slice(0, 200)); window.addEventListener('error', e => { if (!/ResizeObserver/.test(e.message)) errs.push('ERR ' + e.message); });
  const file = (location.hash.slice(1) || 'pedidos.csv');
  S.user = { guest: true }; S.br = { audience: 'director', decision: 'prioritize', time: 'full', message: '', story: null, tone: null, place: null }; for (const k of ['org', 'rays', 'river', 'fan', 'ridge', 'flow']) localStorage.setItem('dv-' + k + '-tutorial', '1');
  D.loadBuffer(file, await (await fetch('/dados-teste/' + file)).arrayBuffer()); for (let i = 0; i < 80 && S.step !== 'preview'; i++) await sl(100); D.go('mapping'); await sl(300); document.querySelector('[data-a=generate]').click(); for (let i = 0; i < 80 && S.step !== 'find'; i++) await sl(150); await sl(500);
  out.step = S.step; const cards = [...document.querySelectorAll('.fd-card')]; out.find = { cards: cards.length, selected: cards.filter(c => c.classList.contains('on')).length, badge: (document.querySelector('.fd-badge') || {}).textContent, first: (cards[0] || {}).innerText && cards[0].innerText.replace(/\n/g, ' | ').slice(0, 120), ctas: [...document.querySelectorAll('.fd-ctas .btn')].map(b => b.textContent.trim()) };
  document.querySelectorAll('.fd-main')[1].click(); await sl(200); out.picked = document.querySelectorAll('.fd-card.on').length + ' ' + S.find.center;
  document.querySelector('[data-a=fd-guide]').click(); await sl(500); out.wiz = { step: S.step, prog: (document.querySelector('.prog .lbl') || {}).textContent, q: (document.querySelector('.sb-screen h2') || {}).textContent.replace(/\s+/g, ' ') };
  out.q1 = { chips: document.querySelectorAll('.sb-chip').length, msg: document.querySelector('#sb-msg').value }; document.querySelector('.sb-chip').click(); await sl(200); out.q1after = document.querySelector('#sb-msg').value;
  const next = async () => { document.querySelector('[data-a=sb-next], [data-a=sb-finish]').click(); await sl(350); };
  await next(); out.q2 = { items: document.querySelectorAll('.sb-list .fd-card').length, on: document.querySelectorAll('.sb-list .fd-card.on').length, note: document.querySelector('.sb-screen .note').textContent };
  await next(); out.q3 = { readings: document.querySelectorAll('.sb-list .fd-card').length }; document.querySelector('.sb-list .fd-main').click(); await sl(200); out.q3picked = S.sb.diag.fact; const dt = document.querySelector('#sb-dtext'); dt.value = 'Depende de poucos itens'; dt.dispatchEvent(new Event('input', { bubbles: true }));
  await next(); document.querySelector('.sb-chip').click(); await sl(200); out.q4 = S.sb.impl.filter(Boolean).length;
  await next(); out.q5 = { crits: [...document.querySelectorAll('.sb-opt strong')].map(x => x.textContent) }; document.querySelector('.sb-opt').click(); await sl(250); out.q5rank = [...document.querySelectorAll('.sb-rank li')].map(li => li.innerText.replace(/\n/g, ' ')).join(' ; '); document.querySelector('[data-a=sb-n][data-v="1"]').click(); await sl(200); out.q5n = S.sb.prio.n;
  await next(); document.querySelector('.sb-chip').click(); await sl(200); const pa = document.querySelector('#sb-pa-0'); out.q6 = { action: pa.value, metrics: document.querySelectorAll('#sb-pm-0 option').length }; const po = document.querySelector('#sb-po-0'); po.value = 'Comercial'; po.dispatchEvent(new Event('input', { bubbles: true })); const pm = document.querySelector('#sb-pm-0'); pm.value = pm.options[1].value; pm.dispatchEvent(new Event('change', { bubbles: true }));
  await next(); document.querySelector('.sb-chip').click(); await sl(200); out.q7 = document.querySelector('#sb-ask').value; out.count = document.querySelector('.sb-count').textContent;
  document.querySelector('[data-a=sb-finish]').click(); for (let i = 0; i < 60 && S.step !== 'editor'; i++) await sl(150); await sl(1500);
  out.final = { step: S.step, title: S.piece.title, sb: Object.keys(S.piece.sb).map(k => k + ':' + (Array.isArray(S.piece.sb[k]) ? S.piece.sb[k].length : typeof S.piece.sb[k] === 'object' && S.piece.sb[k] ? 'obj' : String(S.piece.sb[k]).slice(0, 14))).join(','), toast: (document.querySelector('#toast') || {}).textContent };
  document.querySelector('[data-a=present]').click(); await sl(900); const pr = S.piece.pres; out.pres = pr.steps.map(s => s.kick.n + ' ' + (s.type || s.act) + ' | ' + String(s.head).slice(0, 44));
  out.errs = errs; return JSON.stringify(out, null, 1); })()
