(async () => { const sl = ms => new Promise(r => setTimeout(r, ms)); const D = window.__datavix, S = D.S;
  S.user = { guest: true }; S.br = { audience: 'director', decision: 'prioritize', message: 'Receita por categoria', story: 'compare', tone: 'tech', place: 'screen' }; for (const k of ['org', 'rays', 'river', 'fan', 'ridge', 'flow']) localStorage.setItem('dv-' + k + '-tutorial', '1');
  D.loadBuffer('pedidos.csv', await (await fetch('/dados-teste/pedidos.csv')).arrayBuffer()); for (let i = 0; i < 80 && S.step !== 'preview'; i++) await sl(100); D.go('mapping'); await sl(300); document.querySelector('[data-a=generate]').click(); for (let i = 0; i < 80 && S.step !== 'editor'; i++) await sl(150); await sl(2500);
  const sample = async (sel, ms, step) => { const rows = [], t0 = performance.now(); while (performance.now() - t0 < ms) { const n = document.querySelector(sel); if (n) { const r = n.getBoundingClientRect(), lab = n.nextElementSibling ? n.nextElementSibling.getBoundingClientRect() : null; rows.push({ t: Math.round(performance.now() - t0), txt: n.textContent, w: Math.round(r.width), x: Math.round(r.left), labY: lab ? Math.round(lab.top) : null, labX: lab ? Math.round(lab.left) : null }); } await sl(step); } return rows; };
  const sum = rows => { const nums = rows.map(r => parseFloat(r.txt.replace(/[^0-9.\-]/g, ''))); const sufs = new Set(rows.map(r => r.txt.replace(/[0-9.,\s\-]/g, ''))); return { n: rows.length, first: rows[0].txt, last: rows[rows.length - 1].txt, suffixes: [...sufs], monotonic: nums.every((v, i) => i === 0 || v >= nums[i - 1] - 1e-9), widths: [...new Set(rows.map(r => r.w))], labelPos: [...new Set(rows.map(r => r.labX + ',' + r.labY))].length }; };
  document.querySelector('[data-a=present]').click(); const intro = await sample('.pi-num', 2900, 40); const out = { intro: sum(intro) };
  await S.piece.pres.show(1); const s2 = await sample('.ps-num', 1900, 40); out.slide2 = sum(s2); out.slide2txt = s2.filter((r, i) => i % 6 === 0).map(r => r.txt).join(' > ');
  out.introSeq = intro.filter((r, i) => i % 7 === 0).map(r => r.txt).join(' > ');
  S.piece.pres.stop(); return JSON.stringify(out, null, 1); })()
