(async () => { const sl = ms => new Promise(r => setTimeout(r, ms)); const D = window.__datavix, S = D.S, errs = []; window.addEventListener('error', e => { if (!/ResizeObserver/.test(e.message)) errs.push(e.message); });
  S.user = { guest: true }; S.br = { audience: 'director', decision: 'prioritize', message: 'Receita por categoria', story: 'compare', tone: 'tech', place: 'screen' }; for (const k of ['org', 'rays', 'river', 'fan', 'ridge', 'flow']) localStorage.setItem('dv-' + k + '-tutorial', '1');
  D.loadBuffer('pedidos.csv', await (await fetch('/dados-teste/pedidos.csv')).arrayBuffer()); for (let i = 0; i < 80 && S.step !== 'preview'; i++) await sl(100); D.go('mapping'); await sl(300); document.querySelector('[data-a=generate]').click(); for (let i = 0; i < 80 && S.step !== 'editor'; i++) await sl(150); await sl(2500);
  document.querySelector('[data-a=present]').click(); await sl(800); document.querySelector('.pi-go').click(); await sl(1800);
  const cv = document.querySelector('.orgstage canvas'), r = cv.getBoundingClientRect(); let hit = null;
  for (let fx = .15; fx <= .45 && !hit; fx += .02) for (let fy = .2; fy <= .7 && !hit; fy += .015) { const x = r.left + r.width * fx, y = r.top + r.height * fy; cv.dispatchEvent(new PointerEvent('pointermove', { clientX: x, clientY: y, bubbles: true })); cv.dispatchEvent(new MouseEvent('click', { clientX: x, clientY: y, bubbles: true })); if (document.querySelector('#pcard').classList.contains('pin')) hit = [fx, fy]; }
  const c = document.querySelector('#pcard'), b = c.getBoundingClientRect(), x = c.querySelector('.cardx'); const out = { hit: !!hit, cls: c.className, left: Math.round(b.left), bottom: Math.round(b.bottom), vh: innerHeight, ctxHidden: getComputedStyle(document.querySelector('.pctx')).opacity, closable: !!x };
  const xr = x.getBoundingClientRect(); out.xHit = document.elementFromPoint(xr.left + xr.width / 2, xr.top + xr.height / 2) === x; x.click(); await sl(400); out.afterClose = document.querySelector('#pcard').className; out.ctxBack = getComputedStyle(document.querySelector('.pctx')).opacity;
  out.errs = errs; return JSON.stringify(out); })()
