(async () => { if (location.hash.includes('nodpr')) window.__vidNoDpr = true; if (location.hash.includes('init')) window.__vidInit = 300; const sl = ms => new Promise(r => setTimeout(r, ms)); const D = window.__datavix, S = D.S, errs = [];
  S.user = { guest: true }; S.br = { audience: 'director', decision: 'prioritize', message: 'Receita', story: 'compare', tone: 'tech', place: 'screen' }; for (const k of ['org', 'rays', 'river', 'fan', 'ridge', 'flow']) localStorage.setItem('dv-' + k + '-tutorial', '1');
  D.loadBuffer('pedidos.csv', await (await fetch('/dados-teste/pedidos.csv')).arrayBuffer()); for (let i = 0; i < 80 && S.step !== 'preview'; i++) await sl(100); D.go('mapping'); await sl(300); document.querySelector('[data-a=generate]').click(); for (let i = 0; i < 80 && S.step !== 'editor'; i++) await sl(150); await sl(2500);
  document.querySelector('.panel .type[data-v=hbars]').click(); await sl(2200);
  const P = S.piece, meta = P.host.ix.meta, steps = buildSteps(P, meta), t3 = steps.find(s => s.id === 't3'); const out = { t3: JSON.stringify(t3 && t3.state), filterDim: meta.filterDim, labels: (meta.filterLabels || []).slice(0, 4) };
  const f = makeFilter(meta, { sel: new Set(t3.state.sel), range: null }); out.fnType = typeof f; out.fnOnRows = typeof f === 'function' ? P.built.vz.series.length && ['Eletrônicos', 'Papelaria'].map(l => f({ [meta.filterDim]: l })) : null;
  if (location.hash.includes('detach')) { try { P.host.chart.detach(); out.detached = true; } catch (e) { out.detachErr = String(e); } }
  const mode = location.hash.slice(1);  const viz = await videoVizzu(P, { w: 980, h: 730 }, meta); const hs = viz.cnv.parentElement; if (mode === 'vis') { hs.style.opacity = '1'; hs.style.zIndex = '99999'; } if (mode === 'tiny') { hs.style.opacity = '0.01'; hs.style.zIndex = '99999'; } out.rafOk = await new Promise(r => { let n = 0; const f = () => { if (++n > 5) r(true); else requestAnimationFrame(f); }; requestAnimationFrame(f); setTimeout(() => r(false), 1500); }); const px = () => { const c = viz.cnv, x = c.getContext('2d'); return c.width + 'x' + c.height; }; out.size = px();
  const snapshot = () => { const c = viz.cnv; const t = document.createElement('canvas'); t.width = 98; t.height = 73; t.getContext('2d').drawImage(c, 0, 0, 98, 73); const d = t.getContext('2d').getImageData(0, 0, 98, 73).data; let n = 0; for (let i = 3; i < d.length; i += 4) if (d[i] > 40) n++; return n; };
  out.px0 = snapshot();
  const save = async n => { await fetch('/save?name=vz-' + n + '.png', { method: 'POST', body: await new Promise(r => viz.cnv.toBlob(r, 'image/png')) }); };
  await save('0'); const f3 = makeFilter(meta, { sel: new Set(t3.state.sel), range: null });
  out.keys = Object.keys(viz.chart).concat(Object.getOwnPropertyNames(Object.getPrototypeOf(viz.chart))).slice(0, 40).join(','); out.animKeys = viz.chart.animation ? Object.getOwnPropertyNames(Object.getPrototypeOf(viz.chart.animation)).join(',') : null; out.hidden = document.hidden; out.vis = document.visibilityState; out.focus = document.hasFocus();
  try { const t0 = performance.now(); await within(viz.chart.animate({ data: { filter: f3 } }, { duration: 0.6 }), 3000); out.animMs = Math.round(performance.now() - t0); } catch (e) { out.animErr = String(e && e.message || e); }
  await sl(300); out.px3 = snapshot(); await save('3'); viz.destroy(); return JSON.stringify(out, null, 1); })()
